# Créez le fichier Dockerfile dans le répertoire /frontend.
# Cette image sera basée sur l'image Docker nginx:alpine.
FROM nginx:alpine
# Copiez tous les fichiers dans le répertoire /usr/share/nginx/html de l'image Docker.
COPY . /usr/share/nginx/html